# Site settings
title: CI and CD with GitHub
description: A demo blog
email: david.hirko@carefusion.com
github_username:  davidhirko
baseurl:
url: https://githubtraining-cicd-demo.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

markdown: kramdown
